version: "3.7"

x-user-args:
  &user-args
  APP_USER: ${APP_USER}
  APP_GROUP: ${APP_GROUP}
  APP_USER_ID: ${APP_USER_ID}
  APP_GROUP_ID: ${APP_GROUP_ID}

x-app-volume: &app-volume ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        <<: *user-args
    volumes:
      - *app-volume
    depends_on:
      - database
    command: >
      bash -c "php-fpm"

  nginx:
    image: nginx
    restart: always
    volumes:
      - *app-volume
      - "./configs/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - app
      - database

  database:
    image: mysql
    restart: always
    ports:
      - "9812:3306"
    environment:
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=generic
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=tT7jN0oX0f111

volumes:
  app:
  database: